### ISSUE TITLE
亲爱的程序员您好!

### ISSUE THREAD

**Issue by Edelwiess** [were/progs#1]
得益于您上传的KCBKLogic.dll，我才得以在春季活动捞到U-511.
不知道您是怎样破解的KCBKLogic。
现在KCBK已经发展到0.1.2.9版本了，甚至我用虚拟机日语系统都打不开。
希望阁下能和我交流一下破解kcbk日语系统限制的经验。
我的联系方式：wangxin86@gmail.com
祝您生活愉快！

**Comment by were** [comment]
妈呀，低调，你这一弄大家都知道我是科技党了。
